"""empty message

Revision ID: 95941a1969c2
Revises: 
Create Date: 2018-11-26 22:15:31.028025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95941a1969c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('checkup',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkup_type', sa.String(length=120), nullable=False),
    sa.Column('checkup_report', sa.String(length=120), nullable=False),
    sa.Column('checkup_for_id', sa.Integer(), nullable=True),
    sa.Column('machine', sa.String(length=120), nullable=True),
    sa.Column('taken_by', sa.String(length=120), nullable=True),
    sa.Column('disease', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['checkup_for_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkup_report'),
    sa.UniqueConstraint('checkup_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkup')
    op.drop_table('user')
    # ### end Alembic commands ###
