"""empty message

Revision ID: cc805ab1bc28
Revises: 4cecc0d2ed8a
Create Date: 2018-11-22 23:36:52.397426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc805ab1bc28'
down_revision = '4cecc0d2ed8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkup', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('checkup', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('disease', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('disease', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('machine', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('machine', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'created_on')
    op.drop_column('machine', 'updated_on')
    op.drop_column('machine', 'created_on')
    op.drop_column('disease', 'updated_on')
    op.drop_column('disease', 'created_on')
    op.drop_column('checkup', 'updated_on')
    op.drop_column('checkup', 'created_on')
    # ### end Alembic commands ###
